### ISSUE TITLE
None of the variants got phased and also the tool reported no error

### ISSUE THREAD

**Issue by marcelm** [whatshap/whatshap#221]
**[Original report](https://bitbucket.org/whatshap/whatshap/issue/221) by Dhwani Dholakia (Bitbucket: [dhwani_dholakia](https://bitbucket.org/dhwani_dholakia), ).**

----------------------------------------

Hello,

I have ran whatshap using my data and command and its output looks like this

dhwani@dhwani-HP-Z620-Workstation:~/Documents/PhD/objective2/Phasing/WhatsHap$ whatshap phase --reference ../../reference/b\_ref.fasta -o whatshap\_phased.vcf ../Hapcut2/BAM\_files/DQ\_snps.vcf ../Hapcut2/BAM\_files/DQ\_vqsr.bam

This is WhatsHap 0.18 running under Python 3.7.4

Working on 1 samples from 1 family

======== Working on chromosome '6'

---- Processing individual DQ

Using maximum coverage per sample of 15X

Number of variants skipped due to missing genotypes: 0

Number of remaining heterozygous variants: 0

Reading alignments for sample 'DQ'and detecting alleles ...

Found 0 reads covering 0 variants

Kept 0 reads that cover at least two variants each

Reducing coverage to at most 15X by selecting most informative reads ...

Selected 0 reads covering 0 variants

Best-case phasing would result in 0 non-singleton phased blocks \(0 in total\)

... after read selection: 0 non-singleton phased blocks \(0 in total\)

Variants covered by at least one phase-informative read in at least one individual after read selection: 0

Phasing 1 sample by solving the MEC problem ...

MEC cost: 0

No. of phased blocks: 0

======== Writing VCF

Done writing VCF

‌

== SUMMARY ==

Maximum memory usage: 0.059 GB

Time spent reading BAM/CRAM: 3.4 s

Time spent parsing VCF: 0.0 s

Time spent selecting reads: 0.0 s

Time spent phasing: 0.0 s

Time spent writing VCF: 0.0 s

Time spent finding components: 0.0 s

Time spent on rest: 0.0 s

Total elapsed time: 3.5 s

**Comment by skylerhar1** [comment]
Hello, I seem to be having a similar problem, but I definetly have heterozygous variants ( tested with bcftools view -g het)
`whatshap phase -o nanopore_phased.vcf --ignore-read-groups --reference=/nfs1/BPP/Spatafora_Lab/hars/whatshap_phasing/mip_hd1hd2_bfg-Rsale.fasta /nfs1/BPP/Spatafora_Lab/hars/whatshap_phasing/reference_gvcf/P212_JGI.mapped.R1.fq.gz.g.vcf.gz /nfs1/BPP/Spatafora_Lab/hars/whatshap_phasing/nanopore_bams/mapping.sorted.bam
This is WhatsHap 1.6 running under Python 3.10.6
Working on 1 sample from 1 family

# Working on contig mip_hd1hd2_bfg-Rsale in individual P212_JGI.mapped.R1.fq.gz
Found 0 usable heterozygous variants (0 skipped due to missing genotypes)
Found 0 reads covering 0 variants
Kept 0 reads that cover at least two variants each
Selected 0 most phase-informative reads covering 0 variants
Best-case phasing would result in 0 non-singleton phased blocks (0 singletons).
Phasing 1 sample by solving the MEC problem ...
No. of phased blocks: 0

# Resource usage
Maximum memory usage: 0.035 GB
Time spent reading BAM/CRAM:                    0.0 s
Time spent parsing VCF:                         0.0 s
Time spent selecting reads:                     0.0 s
Time spent phasing:                             0.0 s
Time spent writing VCF:                         0.0 s
Time spent finding components:                  0.0 s
Time spent on rest:                             0.3 s
Total elapsed time:                             0.3 s
`
I can email you privately the files to recreate the issue. The only large file is the raw reads. Any idea what could be going wrong?
