### ISSUE TITLE
invalid choice: 'haplofasta'

### ISSUE THREAD

**Issue by zoeluo15** [whatshap/whatshap#246]
Hi,

I read in the documentation that there is a subcommand called haplofasta, but when I run `whatshap haplofasta --help`, I got the following error (I tried both development version and v1.0)

`whatshap: error: invalid choice: 'haplofasta' (choose from 'compare', 'find_snv_candidates', 'genotype', 'hapcut2vcf', 'haplotag', 'phase', 'polyphase', 'split', 'stats', 'unphase')`

Is haplofasta no longer available in whatshap?

Many thanks,
Zoe

**Comment by tobiasmarschall** [comment]
Dear Zoe,

we removed that years ago (see https://bitbucket.org/whatshap/whatshap/issues/123/describe-how-to-create-haplotype-fasta), because `bcftools consensus` can be used for this. It is described here:
https://whatshap.readthedocs.io/en/latest/guide.html#creating-phased-references-in-fasta-format

Where in the documentation did you read about `haplofasta` we should remove that. Or did you open an old version of the docs?

Best,
Tobias

**Comment by zoeluo15** [comment]
Hi Tobias,
I read it from here https://whatshap.readthedocs.io/en/latest/guide.html, in the subcommand section.
Thanks for link!
Zoe    On Thursday, September 3, 2020, 06:12:48 PM GMT+12, Tobias Marschall <notifications@github.com> wrote:  
 
 


Dear Zoe,

we removed that years ago (see https://bitbucket.org/whatshap/whatshap/issues/123/describe-how-to-create-haplotype-fasta), because bcftools consensus can be used for this. It is described here:
https://whatshap.readthedocs.io/en/latest/guide.html#creating-phased-references-in-fasta-format

Where in the documentation did you read about haplofasta we should remove that. Or did you open an old version of the docs?

Best,
Tobias

**Comment by marcelm** [comment]
The documentation should be fixed now (will be online in a couple of minutes).
