### ISSUE TITLE
Phasing information from Supplementary alignments

### ISSUE THREAD

**Issue by MaestSi** [whatshap/whatshap#247]
Dear WhatsHap developers,
I am phasing variants from ONT reads that present some chimeras due to the enrichment platform we used for obtaining the library. This results in each read aligning as a primary alignment and a set of supplementary alignments. Does WhatsHap use the information provided by Supplementary alignments? Moreover, does it exploit the read name for phasing two variants if these are present in two fragments from the same read that align as two supplementary alignments?
Thanks,
Simone

**Comment by tobiasmarschall** [comment]
Dear Simone,
there's an ancient issue about this: Issue #23. But I think it is still open unfortunately. You can read through the old issue if you like. One of the key questions is how to support supp alignments in a way that helps more than it harms, because quite often supplementary alignments give rise to spurious long-distance connections. Curious to hear your thoughts on how WhatsHap should support supp alignments....
Best,
Tobias

**Comment by MaestSi** [comment]
Dear Tobias,
I read through the issue 23. As said in the previous discussion, there are plenty of SVs in a genome, therefore it is a pity to break the haplo-block in correspondence of those, since there is information in ONT reads for phasing SNVs at both sides of an SV. In general, I would say that a possibility may be to set a minimum MAPQ for WhatsHap to use for filtering the BAM, instead of using the SAM flag. For sure, alignments with MAPQ=0 should be ignored, but otherwise I would try to recover those SA.
Best,
Simone

**Comment by tobiasmarschall** [comment]
Thank. We should really get to this soon. I am closing this one for now and marking it as duplicate.
