### ISSUE TITLE
Old Bai File 

### ISSUE THREAD

**Issue by shacharshani1** [whatshap/whatshap#279]
Hey, 
I am trying to phase a VCF file, I have both BAM and Bai file, but I ran into the following error:

This is WhatsHap 0.18 running under Python 3.6.9

[W::hts_idx_load3] The index file is older than the data file: wgp229.nodup.bam.recal.bai

[E::bgzf_read] Read block operation failed with error 4 after 20 of 32 bytes

[E::hts_idx_load3] Could not load local index file 'wgp229.nodup.bam.recal.bai'

Is the warning can be ignored? what could be causing this issue?
Thank you in advanced,
Shachar

**Comment by marcelm** [comment]
This is an error and should not be ignored. For some reason, the `.bai` file does not match the `.bam` file.

You may want to delete the `.bai` file and regenerate it with `samtools index wgp229.nodup.bam.recal.bam`.

Note also that Whatshap 0.18 is outdated; the current version is 1.0 (but that will probably not make the warning and error messages go away).

**Comment by shacharshani1** [comment]
Thank you,
I have a problem phasing my files.
I am working on Linux and my BAM files are stored on an external server.
When I try to phase the files directly from the server (via samba) I receive the ERROR message I posted.
Surprisingly, when I copied my BAM and Bai files to the desktop, I managed to phase the exact VCF files, without reindex my BAM file.
I can't copy all the file from the external server to the desktop. 
How can I fix this problem?
Thanks in advanced,
Shachar

**Comment by marcelm** [comment]
Is an output file generated at all when you run the command? Or does WhatsHap just stop? It would be helpful if you posted the full command line and output.

WhatsHap uses htslib (also used by samtools) to acces BAM files. Messages like `[W::hts_idx_load3] ...` come from htslib. Those that start with `[W::` are warnings and can sometimes be ignored. The ones starting with `[E::` are errors, and I would expect that the program stops after printing an error. Is that correct?

How exactly do you access the files via Samba? Is a directory on the server mounted on your desktop?

If you have write access to the server or can ask someone who has, then it would be easiest if you could just run `samtools index` on the server. If that isn’t possible, you can work around in the following way: Go to some directory where you have write access and create a symbolic link to the BAM file on the server. Then run `samtools index` on that symbolic link. The index will be created locally. The `.bai` files are small, so that should not be a problem. Finally, run WhatsHap again, but use the symbolic link instead of the BAM on the server.

Here is what I mean (roughly), assuming the BAM file on the server is accessible at `/server/wgp229.nodup.bam.recal.bam`:
```
mkdir ~/newdir
cd ~/newdir
ln -s /server/wgp229.nodup.bam.recal.bam wgp229.nodup.bam.recal.bam
samtools index wgp229.nodup.bam.recal.bam
whatshap phase /path/to/the/unphased/variants.vcf wgp229.nodup.bam.recal.bam
```

**Comment by shacharshani1** [comment]
It worked! Thank you so much for your help!
In addition,
Is it possible to phase only a specific region on a chromosome (Instead of phasing the entire chromosome with `--chromosome chr1`)?
When running `whatshap haplotag` is `alignments.bam` referes to all the samples Bam files (which were used in `whatshap phase`)?

**Comment by ptrebert** [comment]
It looks like the original problem has been solved, so I am closing this issue now. Here are the answers to your additional questions:

> Is it possible to phase only a specific region on a chromosome (Instead of phasing the entire chromosome with --chromosome chr1)?

Not yet; adding a `--regions` parameter to all WhatsHap commands where it makes sense is a feature request on the to do list.

> When running whatshap haplotag is alignments.bam referes to all the samples Bam files (which were used in whatshap phase)?

Not sure I fully understand the problem, but the `haplotag` command can operate in different ways (not detailing everything here, please see the command line help):
- multi-sample VCF and multi-sample BAM: haplotagging is performed for all samples shared between VCF and BAM, or select a specific sample via `--sample`
- single-sample VCF and BAM with multiple samples/read groups: use the switch `--ignore-read-groups` to haplotag all reads in the BAM file irrespective of their read group, i.e., assume all reads pertain to the sample in the VCF
