### ISSUE TITLE
The minimum recommended depth for Nanopore data

### ISSUE THREAD

**Issue by charliechen912ilovbash** [whatshap/whatshap#317]
Hi,
What is the minimum recommended depth for Nanopore data?
If possible, I want to know the minimum recommended depth for Nanopore tumor data.
Thanks.

**Comment by tobiasmarschall** [comment]
I'm afraid there's no simple answer to your question. The answer will depend on (at least) three things: 1) What read length are you generating, 2) how complete do you want your phasing to be, and 3) what is your aim with the tumor data and how much subclonal heterogeneity are you expecting?

**Comment by charliechen912ilovbash** [comment]
1. My N50 is ~3000bp
2. I want to phase >90% of the human genome.
3. My purpose is to make previously detected large somatic structural variant (SV) (>50bp) more clear, especially for complex SV. 

In the original paper of WhatsHap, I think you mention the minimum depth when using PacBio data is around 10x? I am wondering in the same situation, if there are any difference when using Nanopore data. 
The sequencer I am using is PromethION, basecaller is Guppy 3.8.

https://www.biorxiv.org/content/10.1101/085050v2.full

**Comment by tobiasmarschall** [comment]
3000bp is on the shorter end of the (long read) spectrum these days, but given that the average distance between two het SNPs is ~ 1000bp in the human genome, you will be able to get reasonable phased block sizes. If you can bring up read length, that's definitely helpful (especially for resolving SVs). I would, if possible, also recommend more than 10-fold coverage, because that means only 5-fold per haplotype. While phasing might start at work at 10-fold, the low coverage per haplotype limits your ability to resolve SVs...

**Comment by charliechen912ilovbash** [comment]
Sorry for the mistyping, the N50 is ~13,000bp.
I see, I also notice that some other phasing tools need minimum depth ~10x. Thanks for advising.
My tumor sample depth is ~30x.
Just for curious, is it necessary to down-sample the reads if the depth is too high (e.g. >60x or >100x)?

**Comment by tobiasmarschall** [comment]
No, you don't need to downsample as WhatsHap will automatically select a suitable subset of the most informative reads.

**Comment by charliechen912ilovbash** [comment]
I understood, thanks for answering my question!
