### ISSUE TITLE
Found 0 reads covering 0 variants

### ISSUE THREAD

**Issue by EDJONEILL** [whatshap/whatshap#327]
I have a sorted bam file with 121 reads, along with its index file. I also have a bgziped VCF file and its index file from freebayes, which lists 2 heterozygous variants (attached as csv). 
[Sample1.csv](https://github.com/whatshap/whatshap/files/7032855/Sample1.csv)

I have used the command: 

`whatshap polyphase -o output.vcf --reference Sample1.fas --ignore-read-groups --ploidy 6 Sample1.vcf.gz Sample1.sorted.bam`

This gives the message:

This is WhatsHap (polyploid) 1.1 running under Python 3.9.6
======== Working on chromosome 'Sample1'
---- Processing individual unknown
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 0
Reading alignments and detecting alleles ...
Found 0 reads covering 0 variants

Why is it saying there are no heterozygous variants or reads?

Thanks,
Ed

**Comment by schrins** [comment]
Both variants in the CSV are indel variants, which are not included by default. To include them, you have to use the `--indels` flag. However, the second variant is multiallelic and there is currently no support for these variants. So even with the indel flag, only one variant could be processed, which results in a trivial phasing. As for the number of reads: Before phasing, all reads which do not cover at least two variants are kicked out, because they are not informative for the phasing. In this case, this applies to all reads.

**Comment by EDJONEILL** [comment]
I see. It's not really an indel, it's just a series of point mutations, but I can see why the program views it as such. A lot of our data has these multiallelic variants, so I don't think this is the program for us.

Thanks a lot,
Ed
