### ISSUE TITLE
Segmentation fault when running phase

### ISSUE THREAD

**Issue by Mondlii** [whatshap/whatshap#328]
Hi there.

I tried running Whatshap on a VCF file generated from sniffles, and I keep getting a segmentation fault error seconds into the run. Please see below the error file. Thank you for your help.

```
This is WhatsHap 1.1 running under Python 3.9.5
[W::vcf_parse] FILTER 'STRANDBIAS' is not defined in the header
[W::vcf_parse] INFO/END=27956 is smaller than POS at bctg00000002_segment0_segment0_segment0:27957
Working on 1 samples from 1 family
[W::vcf_parse] FILTER 'STRANDBIAS' is not defined in the header
======== Working on chromosome 'bctg00000001_segment0_segment0_segment0'
---- Processing individual /projects/EBP/CBC/pretoria/Acacia_SP644/longstitch/Sniffles_aligned.bam
Using maximum coverage per sample of 15X
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 0
Reading alignments and detecting alleles ...
Found 0 reads covering 0 variants
Kept 0 reads that cover at least two variants each
Reducing coverage to at most 15X by selecting most informative reads ...
Selected 0 reads covering 0 variants
Best-case phasing would result in 0 non-singleton phased blocks (0 in total)
... after read selection: 0 non-singleton phased blocks (0 in total)
Variants covered by at least one phase-informative read in at least one individual after read selection: 0
Phasing 1 sample by solving the MEC problem ...
MEC cost: 0
No. of phased blocks: 0
======== Writing VCF
[W::vcf_parse] FILTER 'STRANDBIAS' is not defined in the header
/var/spool/slurm/slurmd/job3292656/slurm_script: line 41: 3910231 Segmentation fault
```

Mondli.

**Comment by marcelm** [comment]
To fix this, we’d need to be able to reproduce this problem ourselves. Can you make the input files available to us? Since the error occurs very early, abbreviated versions of the filse would be sufficient. Also, we need to know which command-line arguments you used.

It’s possible that the message about the `STRANDBIAS` filter has to do with the problem, but WhatsHap shouldn’t segfault even if it doesn’t like the VCF.

**Comment by Mondlii** [comment]
Thank you for the quick response.

command used is: 

``` whatshap phase -o Phased_sniffle.vcf --ignore-read-groups --reference=/projects/Purged_assembly.fasta /projects/Sniffles_aligned.bam```

Please see below the link to folder with the files 
https:https://drive.google.com/drive/folders/1cVRh0lnpOZqJm5qkfP9726VIMuAsnUNz?usp=sharing

**Comment by marcelm** [comment]
Did you send the right reference FASTA? I get
```
ERROR: whatshap error: Chromosome 'bctg00000001_segment0_segment0_segment0' present in VCF file, but not in the reference FASTA 'WhatsHap/Purged_assembly.fasta'
```
The reference FASTA you sent has these entries:
```
bctg00000000
bctg00000001
bctg00000002
bctg00000003
```
etc.

**Comment by Mondlii** [comment]
Apologies for the mistake and inconvenience, I have reuploaded the file directly from the server instead of the one on my local pc. 

This is what it looks like;

``` >bctg00000001_segment0_segment0_segment0 bctg00000001_segment0_segment0:1.0-6414178.0                                                                                                           >bctg00000002_segment0_segment0_segment0 bctg00000002_segment0_segment0:1.0-6245758.0                                                                                                           >bctg00000003_segment0_segment0_segment0 bctg00000003_segment0_segment0:1.0-6111867.0                                                                                                           >bctg00000004_segment0_segment0_segment0 bctg00000004_segment0_segment0:1.0-6015422.0                                                                                                           >bctg00000006_segment0_segment0_segment0 bctg00000006_segment0_segment0:1.0-5332291.0                                                                                                           >bctg00000005_segment0_segment0_segment0 bctg00000005_segment0_segment0:1.0-5324470.0                                                                                                           >bctg00000000_segment1_segment0_segment0 bctg00000000_segment1_segment0:1.0-5110468.0                                                                                                           >bctg00000007_segment0_segment0_segment0 bctg00000007_segment0_segment0:1.0-5125628.0                                                                                                           >bctg00000008_segment0_segment0_segment0 bctg00000008_segment0_segment0:1.0-5036517.0                                                                                                           >bctg00000009_segment0_segment0_segment0 bctg00000009_segment0_segment0:1.0-4812626.0                                                                                                           >bctg00000010_segment0_segment0_segment0 bctg00000010_segment0_segment0:1.0-4745905.0   ```

Regards,
Mondli

**Comment by marcelm** [comment]
Thanks. I don’t have more time today. I will get back to you as soon as I have time.

**Comment by marcelm** [comment]
In short:
- The VCF file is missing a definition of `STRANDBIAS`
- The VCF file needs to be sorted
- Use `--indels`
- Try to get rid of the `N` in REF/ALT in the VCF

The long version follows.

With the new files, I get this:
```
[W::vcf_parse_filter] FILTER 'STRANDBIAS' is not defined in the header
[E::vcf_format] Invalid BCF, the FILTER tag id=27 at bctg00000001_segment0_segment0_segment0:341667 not present in the header
Traceback (most recent call last):
[...]
  File "pysam/libcbcf.pyx", line 4419, in pysam.libcbcf.VariantFile.write
  File "pysam/libcbcf.pyx", line 4456, in pysam.libcbcf.VariantFile.write
OSError: [Errno 22] b'Invalid argument'
```
Your error message is different, and I am not sure why, but in case, WhatsHap appears to have problems with the VCF file. To check whether that is the case, I run `whatshap unphase Sniffled.vcf > /dev/null`, which gives me the same error:
```
[W::vcf_parse_filter] FILTER 'STRANDBIAS' is not defined in the header
[E::vcf_format] Invalid BCF, the FILTER tag id=26 at bctg00000001_segment0_segment0_segment0:341667 not present in the header
```
(Even just `bcftools view` complains.) As the message says, the problem is that the filter `STRANDBIAS` is not listed in the header. I edited the VCF and added this line to the header (after the existing `##FILTER` line):
```
##FILTER=<ID=STRANDBIAS,Description="strand bias">
```
With that, WhatsHap actually runs, but because the VCF file is unsorted, no phasing is actually done. I fixed that with `bcftools sort Sniffled.vcf > sorted.vcf`. Also, because the VCF contains many indels, you need to add `--indels` to the WhatsHap options.

Finally, the phasing is still bad because the REF or ALT fields in the VCF are very often just `N`. I’m not sure whether that is a Sniffles thing or whether you need to change the way in which you invoke it, but WhatsHap can only phase variants for which exact sequence information is available.

**Comment by Mondlii** [comment]
Thank you very much for the extensive effort and help that you've provided to me with this issue. I will look to finding a new and robust variant caller for my reads (Nanopore) and see how I progress going forward. I had some Freebayes output but the run never finished so I couldn't reliably use the results. 

Thank you very much for the help with this.

**Comment by marcelm** [comment]
Thank you very much for getting back and being so kind!
