### ISSUE TITLE
More documentation/methods for whatshap compare?

### ISSUE THREAD

**Issue by rlorigro** [whatshap/whatshap#349]
Hi,

My labmate and I have been using your `whatshap compare` tool for evaluation of phasing, using the GIAB HG002 VCF as a reference, and it has been very convenient. However, we would like to be able to share these results more widely and we are not confident about how exactly your methods determine switch rate and hamming error. A brief method explanation would be super helpful. For example, some questions we have are:

1. How does the comparison deal with variants for which alleles in the query do not match alleles in the reference? 
2. Does hamming error take into account these non-matching alleles? 
3. Does a single trans oriented pair of adjacent heterozygous variants constitute 1 switch?

**Comment by marcelm** [comment]
Hi, I just wanted to acknowledge that we saw your message. Some of us are still on vacation, so give us a little bit of time to reply. (Remind us at the end of next week if we haven’t gotten back to you.)

**Comment by Chenglin20170390** [comment]
hi I have a same question, how to understand switch and hamming error here? 

And, I do have one more question, I would like to check phasing quality of my haplotype resolved genome from a diploid species.
 
1) I mapped hifi reads to hap1 genome and then calling variation  with deepvariant, and phasing with whatshap to produce `reads.phase.vcf`.

2) I also aligned hap2  to hap 1 genome by nucmer, and call snp with  show-snps, then convert snps file to produce ` asm.phase.vcf` vcf  with genotype `0|1 `

Then, I would like to compared the phasing quality of my assembly by `whatshap compare ` with two file 1)`reads.phase.vcf` 2) ` asm.phase.vcf` .

I am not sure this is ok or not?  expecially about adding phased genotype` 0|1 ` in asembly. Do you have any suggestion about comparing phasing quality of reads with assembly?

  Thanks in advance.

**Comment by marcelm** [comment]
Hi @rlorigro and @Chenglin20170390, thanks for your patience and thanks for your questions. I’m currently trying to add some documentation for `whatshap compare`, and the questions help me decide what needs to be explained.

I’ll try to answer some of your questions. I’ll assume diploid data – I haven’t understood myself how it works for higher ploidies (or whether it works at all).

> How does the comparison deal with variants for which alleles in the query do not match alleles in the reference?

First, note that we don’t use the terms "query" and "reference" within `whatshap compare` because the comparisons are symmetric, and also because you can provide more than two files, in which case comparisons for all possible pairs of files are made.

`whatshap compare` only looks at identical variants when it compares two files. So if you have a variant at a position and it is A&rarr;C in one file and it is A&rarr;G in the other file (at the same position), then these are considered different variants, and they are excluded from comparisons.

Is that what you meant?

> * Does hamming error take into account these non-matching alleles?

No.

> * Does a single trans oriented pair of adjacent heterozygous variants constitute 1 switch?

No, it’s two switches. But `whatshap compare` also detects adjacent switches, which are called *flips*.

Here is some example output from `whatshap compare`:
```
                        switch errors:      2504
            switch/flip decomposition:  284/1110
```
The *switch errors* gives the number of switch errors. Here, two adjacent switches get no special treatment and are just counted as two switches.

The *switch/flip decomposition* then breaks this down into "switches that aren’t part of a flip" and "flips". You can see that this is the case because 284 + 2*1110 = 2504. (So each flip contributes two "normal" switches.)

@Chenglin20170390
> how to understand switch and hamming error here?

Do you mean to ask what a switch error is? Let’s say you have two variant files A and B and the two phase sets have these phased genotypes:
```
A  B
0|1 0|1
0|1 0|1
0|1 1|0
1|0 0|1
1|0 0|1
```
You can write down the first haplotype of file A as 00011 and the first haplotype of file B as 00100 (and the second haplotype of A as 11100 and the second of B as 11011). When counting the errors between them, `whatshap compare` detects *one* switch error between the second and third position because the first haplotype in A matches the first haplotye in B at positions one and two, but then the first haplotype matches the *second* haplotype from position three onwards.

The Hamming distance counts the positions at which the haplotypes differ. For example, comparing 00000 to 00011 gives a Hamming distance of 2 because the haplotypes differ (in the last two alleles), while it would incur only one switch error.

Also, any comparisons `whatshap compare` makes allow the roles of "first' and "second" haplotype to be reversed. For example, when the first haplotype of A is 00000 and the first haplotype of B is 01111, you might guess that the Hamming distance would be 4, but that is not the case because `whatshap compare` notices that it is better to instead compare against the second haplotype of file B (which is 10000), resulting in Hamming distance of just 1.

Regarding the haplotype-resolved genome, I think this analysis sounds ok, but you should be aware that you’re essentially just comparing the way your assembler resolved the haplotypes vs. how WhatsHap did it. You may not be able to deduce an actual phasing quality from this, just an idea of how much these two methods agree.

**Comment by Chenglin20170390** [comment]
Dear Prof Marcel Martin,

Thank you so much for your patient explanations and reminders, I totally get it now. This completely solved my problem.

Happy new year~ 

Best,
Lin

**Comment by marcelm** [comment]
You’re welcome! (But I am not a professor.)

**Comment by rlorigro** [comment]
Thanks a lot Marcel, this is good to know. 

To clarify your flip definition:
```
A   B   C 
0|1 0|1 0|1 
0|1 0|1 0|1 
0|1 1|0 1|0 
1|0 0|1 1|0 
1|0 0|1 1|0 
```
The A to B comparison contains one switch, whereas A vs C contains one flip (two switches). Is that correct? Is it only classified as a flip when switches are immediately consecutive?

**Comment by marcelm** [comment]
> The A to B comparison contains one switch, whereas A vs C contains one flip (two switches). Is that correct?

Yes.

> Is it only classified as a flip when switches are immediately consecutive?

Also yes!

I’ll add your example to the documentation if you don’t mind.

**Comment by marcelm** [comment]
I’ve added as much `whatshap compare` documentation as I had the energy, so I’ll close this now. The section should be visible soon at https://whatshap.readthedocs.io/en/latest/guide.html#whatshap-compare-comparing-variant-files .

**Comment by rlorigro** [comment]
Thanks again for being so helpful with this

**Comment by rlorigro** [comment]
Hi @marcelm 

Sorry to revisit this again, but I was wondering if you could clarify something about absolute vs relative phase assignments. In your example A, if you have a perfectly inverted series of genotypes in sample D:

```
A   D   
0|1 1|0 
0|1 1|0 
0|1 1|0 
1|0 0|1 
1|0 0|1 
```
How many switches would exist between A and B, and what would their hamming error be? This could happen if for ecample you do not know the assignment of paternal/maternal for one sample, but you have de novo phasing.

**Comment by marcelm** [comment]
These phasings are considered to be identical, so they result in zero switch errors and a Hamming distance of zero.

Internally, the comparison is made twice: A is compared to D as-is and then A is compared to the inverted version of D. The result is whatever results in the lowest cost.

**Comment by rlorigro** [comment]
Ahh ok thank you so much for the quick reply. This simplifies things for us greatly.

**Comment by rlorigro** [comment]
One more question, over what range is that comparison computed? Phase sets? contigs? For example, if our sample D has many smaller phase blocks on the order of Mbp which may be randomly inverted or not compared to phase A.

**Comment by marcelm** [comment]
This is done per phase set (I was assuming above that A and D were phase sets).

**Comment by marcelm** [comment]
And to be a bit more precise: If the phase sets of the two samples aren’t exactly identical, then they are split up into "intersection blocks" (that’s the term used in the output). The comparison is made for each of intersection blocks.

**Comment by rlorigro** [comment]
Ok. I'm wondering whether it is sufficient for only one of the samples to have phase sets. For our use case, one sample is the GIAB dataset, and the other is the output of dipcall for a phased assembly. I think we would like to build phase sets for each of the contigs in the dipcall VCF, say, with PS: 1-n and then have the GIAB vcf have PS = 0 throughout the entire VCF. Would this have the intended effect, relying on your intersection blocks? Or do they need to both share matching PS IDs?

**Comment by rlorigro** [comment]
And one last question, does whatshap compare use all variants for which alleles are identical? Including indels? or only SNPs?

**Comment by marcelm** [comment]
> Would this have the intended effect, relying on your intersection blocks? Or do they need to both share matching PS IDs?

The phase set IDs don’t need to match, so this should work as intended.

Also, I think you don’t even have to set PS=0 in the GIAB dataset. In the VCF spec it says: "All phased genotypes that do not contain a PS subfield are assumed to belong to the same phased set." And WhatsHap should honor this. So you’d only need to ensure the GT field contains phased variants.

Regarding numbering the phase sets from 1 to n in the dipcall file, this is totally fine, but it’s probably just as easy to do it as the spec suggests: "The recommended convention is to use the position of the first variant in the set as the PS identifier (although this is not required)." It doesn’t make a difference for `whatshap compare`, but when looking at a raw VCF, it is somewhat helpful to be able to see where the phase set starts, just in case it’s needed.

> does whatshap compare use all variants for which alleles are identical? Including indels? or only SNPs?

Unless you use `--only-snvs`, it will also look at non-SNVs, including indels.

**Comment by rlorigro** [comment]
Hi again, 

I'm trying to dig into our results some more, and I am wondering if there is sufficient data in the output of whatshap compare to produce a list of contiguous switch lengths and their locations.

e.g. this relationship

```
Pos A    B   
0   0|1  1|0 
1   1|0  0|1 
2   0|1  1|0 
3   1|0  0|1 
4   1|0  0|1 
5   0|1  1|0 
6   0|1  1|0 
7   0|1  1|0 
```
would produce this output:
```
Pos Length
1   1
3   2
```
I guess the simplest way to do this would be to have a VCF containing all the switched variants?

If you have any thoughts/advice please let me know.

Thanks

**Comment by marcelm** [comment]
Hm, I guess I don’t understand. In your example, the haplotypes of A and B are just swapped, so there are no switch errors (see your question at https://github.com/whatshap/whatshap/issues/349#issuecomment-1034178386).

**Comment by rlorigro** [comment]
Oh sorry, I edited my example

**Comment by marcelm** [comment]
Hm, not sure because I haven’t used it myself, but could you use `--switch-error-bed` for this?

**Comment by rlorigro** [comment]
Thanks I checked this BED track out in IGV, and here is our chr8, which has a 1.6% hamming error
![image](https://user-images.githubusercontent.com/28764332/199607623-1cd5aa70-e2ad-40fd-ac55-eb1bf20c26c4.png)

However, it looks like this for chr7, which has a 0.08% hamming error:
![image](https://user-images.githubusercontent.com/28764332/199607915-730db109-43bb-4b1d-a33a-3f17d6a46335.png)

So it's not immediately clear where the error is coming from, from this output. It would be super helpful for diagnostics purposes if we could identify where the majority of the switched variants are.

**Comment by marcelm** [comment]
The track shows the switch errors. There are very few on both chromosomes, which is great, and if you want to know where switch errors occur, this track should give you what you need to know. However, you mention Hamming error rates, and these are different.

Maybe I’m missing something, but at least to me, the Hamming error rate is not very useful because a single switch error in the middle of a phased block results in one half of its alleles to be counted as errors. The switch errors are better suited for assessing phasing quality, at least for read-based phasing. I don’t know if it would be different for statistical phasing (you haven’t said what you use).

**Comment by rlorigro** [comment]
These results are from a de Novo assembly using Shasta + GFAse, and the variants are called using dipcall with hg38 as a reference. Since the assembly was generated with very long reads, we generally believe the flips to be noise, or at least caused by a different mechanism than the sustained switches.

My goal in the previous post was to point out that I don't know which of these switches is the one that's resulting in a sustained block of errors and which of these are just single variant flips. It would help a lot with our development if we could differentiate those. 

If you prefer, we could talk more over email or slack. My email is my username @ucsc.edu

**Comment by Han-Cao** [comment]
Hi @rlorigro,

Sorry to bother. I am very interested in the switch error report that you described in this issue. May I know if you have a solution to do similar thing?

Thank you very much!

> e.g. this relationship
> 
> ```
> Pos A    B   
> 0   0|1  1|0 
> 1   1|0  1|0 
> 2   0|1  1|0 
> 3   1|0  1|0 
> 4   1|0  1|0 
> 5   0|1  1|0 
> 6   0|1  1|0 
> 7   0|1  1|0 
> ```
> 
> would produce this output:
> 
> ```
> Pos Length
> 1   1
> 3   2
> ```
