### ISSUE TITLE
How to interpret HS field in whatshap polyphase?

### ISSUE THREAD

**Issue by OmarOakheart** [whatshap/whatshap#353]
Hello,

I'm testing whatshap polyphase on a triploid with the --include-haploid-sets but I don't understand how to interpret it. Here is a (heavily simplified) part of a vcf file output by whatshap polyphase for a triploid:

#chrom    position    ref    alt    GT    PS    HS
NC_001133.9     9786    T       C       0|1|0   2422    1,2,1
NC_001133.9     9931    C       T       0|1|0   2422    1,2,1
NC_001133.9     10186   G       A       1|0|1   2422    2,1,2
NC_001133.9     11102   C       A       1|0|0   11102   2,1,1
NC_001133.9     11719   G       C        0|0|1   11719   1,1,2
NC_001133.9     11866   A       G       0|0|1   11719   1,1,2
NC_001133.9     12118   C       T        0|0|1   11719   1,1,2
NC_001133.9     12195   T       C       0|0|1   11719   1,1,2
NC_001133.9     13171   T       C       0|0|1   11719   1,1,2
NC_001133.9     13542   T       C       1|0|0   13542   2,1,1

I understand that here I have four haplotype blocks: 2422, 11102, 11719 and 13542. However I don't understand what information I can extract from the HS field. It looks like it's just a copy of the GT field but with "," instead of "|", 1 instead of 0 and 2 instead of 1? What is HS supposed to represent?

Best,
Omar

**Comment by schrins** [comment]
The HS-field is a non-standard field. The purpose of this is basically a generalization of the PS-field, but for each haplotype separately. The reason why this was implemented is, that whenever the phasing is decided to be separated, there have been two or more haplotypes, where the phasing could not be linked from one variant position to the other. For a triploid sample you might have three phasings A, B, C for up to position x and three phasings A', B' and C' from position x+1 onward, but you only know that A and A' belong together. For the others either B-B' and C-C' could be true or B-C' and C-B'. In this case you would put variants x and x+1 into different blocks. However, since not all haplotype are disconnected for every cut, we thought we would put this information into a separate custom field. The first phase would have the same block id for x and x+1, while the other two phases have different ids (like the PS field).

So far the theory. Your output, however, looks indeed weird. It's quite some time ago since I worked on this, but it could be that the HS does not use the same block numbering as the PS-field. Instead, it just starts at 1 and counts up by 1, whenever a new block starts on one of the phases. But even then, you should never observe decreasing block ids like you go from the second to the third row in your output. Moreover, as you pointed out, the block ids are identical to the genotype field with numbers just being exactly 1 higher. I cannot really on the spot what is going on there, I would have to investigate this in the code.

**Comment by OmarOakheart** [comment]
Thank you for the quick response. Your description of how it should work is how I thought it would function based on reading the -h message. I can share any data you might need to recreate and identify the issue.

**Comment by schrins** [comment]
Sorry, I totally forgot to continue this ...
I think I found the error in the code and created a branch "issue353" for this. Can you maybe clone this branch and test if the issues still exist for your input data? If you use conda, there is a description how to set this up, because whatshap has a few dependencies: https://whatshap.readthedocs.io/en/latest/develop.html

If you don't want to do this, you could also send me a small instance to test it myself.

**Comment by OmarOakheart** [comment]
I looked at the changes in the issue353 and instead of redownloading a whole new version I modified the vcf.py file to replace
`phases[pos]` with `haploid_components[pos]`

In my test with the modified vcf.py file it now works as expected, thank you for the quick fix.

Example output with the modified vcf.py file:

NC_001133.9     3187    T       C       1|1|0   2372    2372,2372,2372
NC_001133.9     3207    A       G       1|1|0   2372    2372,2372,2372
NC_001133.9     4738    G       A       1|0|0   4641    4641,4641,2372
NC_001133.9     6972    A       G       1|0|0   4641    4641,4641,2372
NC_001133.9     7130    A       G       0|0|1   4641    4641,4641,2372

**Comment by OmarOakheart** [comment]
Will this fix be included in the main whatshap release?

**Comment by marcelm** [comment]
@schris Shall I merge the `issue353` branch into main? We can then make a new release.

**Comment by schrins** [comment]
Yes, I don't see a reason against this.

**Comment by marcelm** [comment]
WhatsHap 1.3 with the fix is now be available on PyPI and Bioconda.
