### ISSUE TITLE
the meaning of NG50 = 0

### ISSUE THREAD

**Issue by charliechen912ilovbash** [whatshap/whatshap#389]
Hi,
Could you explain a little bit about the meaning of NG50 = 0 in the `whatshap stats` output ?
Some of my result showed that NG 50 = 0, but I though it should be at least 1 bp.
Thanks!

**Comment by pontushojer** [comment]
Hi @charliechen912ilovbash, I can maybe bring so clarity here since I looked at the relevant code recently. 

A NG50 of 0 means that your total phase block length does not add up to 50% of the total genome length. If you look at the `Sum of lengths` statistic you will se that this is probably less that 50% of the total genome length. 

See the relevant code snippet below
https://github.com/whatshap/whatshap/blob/80266b3fe2baa2d85e2314fe949ee67ced77f706/whatshap/cli/stats.py#L154-L161

**Comment by charliechen912ilovbash** [comment]
Thanks, I also got the same conclusion after inspecting the all block sizes.
