### ISSUE TITLE
Whatshp is the only tools to phase INDEL, correct? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [whatshap/whatshap#391]
Whatshp is the only tool to phase INDEL, correct?  What about CNV? Thanks.

**Comment by schrins** [comment]
Every variant that is defined in the input VCF should be detectable and phasable, if the `--indels` flag is set. Deletions can be tricky, though, because you could potentially create inconsistent input VCFs, for example:

```
#CHROM  POS ID	REF     ALT QUAL    FILTER  INFO	FORMAT	SAMPLE1
chr1    10  .	AAAAA	A	.       .       .       GT      0/1
chr1    11  .	A       C	.       .       .       GT      0/1
```

One haplotype has the deletion at position 10 (so positions 11 to 14 are not present on one haplotype). But there is also a SNP at position 11, where one haplotype is supposed to have the A-allele and the other one the C-allele. This would be a contradiction to one haplotype having the position deleted. I am not sure how whatshap would handle such a case.

As for CNVs, it depends how they are specified. Whatshap does not look at the reads to figure out possible CNVs itself. It will only look at what variants are specified in the input VCF and what genotype is expected. If the CNV is explicitly given as a deletion or insertion with already determined genotype, it will be phased accordingly, but otherwise it will not.

**Comment by marcelm** [comment]
Deletions overlapping SNVs are currently not detected; this is issue #103.

**Comment by schrins** [comment]
Closing for now, as there seem to be no follow-up question. Feel free to re-open, if there is more to discuss.
