### ISSUE TITLE
strange values of whatshap stats

### ISSUE THREAD

**Issue by GuidoGallo** [whatshap/whatshap#400]
Good morning, I had a very strange result when computing phasing statistics on a phased vcf file from illumina data.
I'm using WhatsHap v1.4 (installed with conda) and I'm using python Python 3.9.12.
I used the command 
whatshap stats file_phased.vcf --tsv=file_stats
not providing the file with contig lengths as they are included in the vcf header.
The tsv file shows 0 in the column block_n50 so, if I understood correctly, it means that the length of phased block did not reach 50% of contig length (which is totally expectable due to the type of genomic data). However, what is strange is that the value bp_per_block_sum is a lot higher than the total length of the chromosome, for most of them. I don't get what is going on, does anyone have any ideas? It should be the total sum, in bp, of all phased blocks right?
 Thanks a lot, would appreciate your help.

Guido

**Comment by marcelm** [comment]
Good afternoon :smile:

Is there a way for us to get access the file? That would make it easier to say what is going on.

**Comment by GuidoGallo** [comment]
thank you very much. The vcf file is in here
https://drive.google.com/drive/folders/1zEj1V3s7_XjlugzbR6pZu9Er6ApyPnOP?usp=sharing

**Comment by marcelm** [comment]
Thanks, that was very helpful! I think I found what the problem is but still need to decide what to do about it.

I looked at the first chromosome `SUPER_3`. It turns out that it contains a couple of phased blocks that span a very large range of bases. For example, there is a phased block consisting of two variants, the first at position 37381135 and the second at position 112477011. There are many other phased blocks in between these positions. In order to avoid inflating the NG50 for such nested or interleaved phase blocks, they are split up into smaller, nonoverlapping blocks and the NG50 is computed from those split blocks. (And yes, 0 means that the block sizes do not add up to 50% of the chromosome size.)

However, the other basepair-based block length statistics (sum of lengths, median block length, average block length, longest block) are computed from the original blocks, so these *do* get artificially inflated. This is why you see a "Sum of lengths" that is larger than the number of chromosome length.

We may need to change this so that the latter statistics are also computed from the split blocks.

@pontushojer Since you recently worked on the block splitting algorithm, do you have an opinion or this?

I’ll probably not be able to work more on this for the next two weeks or so. If you need a meaningful statistic in the meantime, I’d suggest to mostly look at the median, which shouldn’t be influenced by these outlier block sizes so much.

**Comment by pontushojer** [comment]
I found it a bit confusing that block lengths are computed differently within this section when I last worked on the code. I would be positive to a change where every statistic is computed on the split blocks. IMO its a more fair measure of the phasing as a whole. 

I am thinking however about cases where it might be useful to run it on the original blocks.  For example if you have a lot of rearrangements that would cause the blocks to appear interleaved. One option would be to include an option for not splitting the blocks. Something like `--nosplit` where you could compute the statistic on the original blocks.

**Comment by GuidoGallo** [comment]
Thanks a lot for the clear and helpful answer! I stil need to figure out why I get that huge block but that's another story! I will take into account the median in the meanwhile, many thanks again
