### ISSUE TITLE
whatshap haplotag and split for polyploid

### ISSUE THREAD

**Issue by fangdm** [whatshap/whatshap#408]
Hi, I am using whatshap to analyze polyploid data, and when I run 'whatshap haplotag',  I find that it can't handle polyploid data, there is no "--ploidy" parameter. The results of haplotag are shown as diploids (H1, H2 and none) in resule "haplotypes.tsv".
Any ideas on how to fix for polyploid?

the command as:
whatshap haplotag -o haplotagged.bam --reference ref.fa phased.vcf.gz aln.best.sort.bam --output-threads=5 --ignore-read-groups 
--output-haplotag-list haplotypes.tsv

Thank you.

Whatshap version 1.6

**Comment by fangdm** [comment]
it's previous command as:
whatshap polyphase -o phased.vcf --reference=ref.fa --mapq 20 --ploidy 3 -t 1 --indels --ignore-read-groups --distrust-genotypes  variants.vcf aln.best.sort.bam

"variants.vcf" was based on  FreeBayes with illumina, and "aln.best.sort.bam" from HIFI data mapping.

Thank you.

**Comment by schrins** [comment]
I never participated in the haplotag command, but there was supposed to be a polyploid version of it at some point. I think it's still hidden in the `polyploid-haplotag` branch, which is based on quite an old whatshap version now. I might have a look at this, when I have the time, because it is a useful feature, but I can make no promises.

**Comment by Adamtaranto** [comment]
Polyploid haplotagging would be super useful! 1++ for this feature.
