### ISSUE TITLE
Why aren't all heterozygous variants phased?

### ISSUE THREAD

**Issue by smf96** [whatshap/whatshap#438]
Hello,

I have been looking in the documentation but can't find the answer. What is the reason for only ~90% of my heterozygous variants being phased by WhatsHap? Do they have to meet a certain criteria to be phased?

Thank you!

**Comment by schrins** [comment]
There are a few reasons why variants can remain unphased.

By default, only SNPs will be phased. The `--indels` flag adds indels as well, but there are some restrictions: Insertions are usually unproblematic, because they can be handled as "point events" from a reference genome's perspective. Deletions, though, will only be considered if they do not overlap any following heterozygous variants. Otherwise it would not be clear how to interpret the genotypes. Also, multi-allelic variants cannot be handled as of now and will be skipped while reading the VCF file.

Outside the VCF, variants might remain unphased if they are not covered by informative reads, i.e. reads that cover at least two variant.

**Comment by schrins** [comment]
Closing for now, as there seem to be no follow-up questions.
