### ISSUE TITLE
Ploidy Error when the number of haplotypes are three

### ISSUE THREAD

**Issue by masterzhen119** [whatshap/whatshap#444]
Hi!
My python version is:3.9.12 and the version of whatshap is 1.6.
I install the tool via conda
I use the following command
`whatshap  polyphase unadjusted.vcf 0.bam.sorted.bam --ploidy 3 --reference 0_0_reads_reference.fasta --ignore-read-groups --indels -o output2.vcf
`
The unadjusted.vcf  is generated via freebayes as suggested. However, the real number of haplotypes is 3. Since I manually generated the data. Each SNV would be bi-alleic. However, the codes reports:
`ERROR: whatshap error: Inconsistent ploidy (3 and 2)
`
So, what should I do? Or Whatshap can take care of this situation?

Another problem is that: Even if I set `-p=2`, the output vcf is same as the original input vcf. Should I genotype it via the command `whatshap genotype` following with `whatshap polyphase`?

**Comment by schrins** [comment]
The error should only occur if the VCF contains a variant with ploidy different from the specified one. The reason is that WhatsHap needs the genotypes, which are only valid if the ploidy matches. Can you check whether this the case for your input?

Regarding `whatshap genotype`, this only supports diploid genotyping as far as I know, so this needs to be done by another tool. A very hacky way would otherwise be to set every genotype 0/0/1 and run `polyphase` with `--distrust-genotypes`, but the phasing results could suffer quite a bit, if the input genotypes are already completely off.

**Comment by masterzhen119** [comment]
Thanks for your quick reply!
So, I inspect the vcf files generated by the freebayes. It is very strange that the DG tag is 0/0 for all variants. Is that the reason that whatshap polyphase fails? If so, I just wonder that are there any suggestions for detection of SNP which are haplotypes-aware?
I am so impressed by the work of extension of whatshap in ploid case.

Also, I want to make sure one thing: the pipeline before `whatshap  polyphase` is SNP detection following with genotyping?

**Comment by masterzhen119** [comment]
I attached the files below: bam and reference, together with the vcf called by the freebayes.
[0_0_reference_bam_vcf.zip](https://github.com/whatshap/whatshap/files/11139694/0_0_reference_bam_vcf.zip)

**Comment by masterzhen119** [comment]
I update my process:
I find the problem rooted in freebayes, which is set ploidy number = 2 as default. However, even though I change the ploidy number as 3 in the command of the freebayes. I got the 0/0/0 in the DG tag of the VCF file.
After that I set the `--distrust-genotypes` in the whatshap. The output vcf file is the same as the original input vcf, in which all the DG tag variants are 0/0/0. Still, it is strange.

**Comment by schrins** [comment]
If all genotypes are 0/0/0, then these variants will be skipped when reading the VCF. Variants that homozygous in the input cannot become heterozygous in the output. However, when using `--distrust-genotypes` a variant that was heterozygous in the input can become homozygous in the output. I usually do not run variant calling myself, but I had the issues with Freebayes in the past: It finds variant positions, but does not assign any meaningful genotype to them. I once used GATK for this purpose and it at least created useful genotypes, but I cannot tell how good the quality of these were. All other tools I looked for only could genotype diploids, though.

About the general pipeline: Usually after you got sequencing data, you would first use a variant caller (e.g. freebayes) to create a VCF file with three pieces of information: What positions contain variation, which alleles do exist for every variant and what is the genotype of the used sequencing data. The first two are provided by freebayes, but the third one is not.

I opened your VCF file and replaced all `0/0` with `0/0/1` (and also added a header line `##contig=<ID=modify,length=7000,assembly=0_0_reads_reference.fasta>` because every contig/chromosome has to be declared in the header). After that, I could run WhatsHap using the command

`whatshap polyphase unadjusted.vcf 0_0_.bam.sorted.bam -r 0_0_reads_reference.fasta -p 3 --distrust-genotypes --ignore-read-groups -o test.vcf `

It seems to work, but WhatsHap was never designed with the intent to do polyploid genotyping. A specialized variant caller should in theory do more accurate genotype calls.

**Comment by masterzhen119** [comment]
Thanks for your great help!

**Comment by masterzhen119** [comment]
> If all genotypes are 0/0/0, then these variants will be skipped when reading the VCF. Variants that homozygous in the input cannot become heterozygous in the output. However, when using `--distrust-genotypes` a variant that was heterozygous in the input can become homozygous in the output. I usually do not run variant calling myself, but I had the issues with Freebayes in the past: It finds variant positions, but does not assign any meaningful genotype to them. I once used GATK for this purpose and it at least created useful genotypes, but I cannot tell how good the quality of these were. All other tools I looked for only could genotype diploids, though.
> 
> About the general pipeline: Usually after you got sequencing data, you would first use a variant caller (e.g. freebayes) to create a VCF file with three pieces of information: What positions contain variation, which alleles do exist for every variant and what is the genotype of the used sequencing data. The first two are provided by freebayes, but the third one is not.
> 
> I opened your VCF file and replaced all `0/0` with `0/0/1` (and also added a header line `##contig=<ID=modify,length=7000,assembly=0_0_reads_reference.fasta>` because every contig/chromosome has to be declared in the header). After that, I could run WhatsHap using the command
> 
> `whatshap polyphase unadjusted.vcf 0_0_.bam.sorted.bam -r 0_0_reads_reference.fasta -p 3 --distrust-genotypes --ignore-read-groups -o test.vcf `
> 
> It seems to work, but WhatsHap was never designed with the intent to do polyploid genotyping. A specialized variant caller should in theory do more accurate genotype calls.

Thanks for your great help!

**Comment by masterzhen119** [comment]
Thanks for your help! I successfully get the inferred result. One more question:
If one locus is ploid-alleic, i.e. 3, should I replace 0/0/0 to 0/1/2?
Also, the inferred result does not involve indel inferred by AltHap. So, is it rooted in the feature of WhatsHap?

**Comment by schrins** [comment]
Multi-allelic variants are not yet supported in the main version of WhatsHap. It is currently developedin the `mav-polyphase` branch, but it is not finished yet. I don't know exactly how AltHap works, but WhatsHap can phase indels with the `--indel`flag. There are some limitations though. If the indels are very long, it is hard to detect them properly on the reads, because for each read the algorithm has to decide which variants it overlaps and which alleles it takes on each variant. Also, long deletions can be problemaitc if they overlap other variants. There is some old issue about this (#103 ). For now, you cannot get more indels phased than what the `--indel` flag phases by itself.

**Comment by masterzhen119** [comment]
Okay! I understand! Again, thanks for your great help!
