### ISSUE TITLE
Follow up on issue #351

### ISSUE THREAD

**Issue by sstwins21** [whatshap/whatshap#465]
Hi, 

I know it has been a long time, but I want to follow up on the issue #351.
Does whatshap managed to consider more than one alternative allele now?

If it doesn't, for a diploid that has genotype of 1/2, would it be okay to edit the refence allele in VCF file so that that it would include those two allele with genotype 0/1? Of course I need to change the reference column back to way it was when I try to make the consensus. But I am wondering if it would cause error in whatshap phasing.

Kind regards
Shane

**Comment by schrins** [comment]
For `whatshap polyphase` multi-allelic variants should be supported work now. The diploid version, however, uses a different algorithm and I believe the situation is, that MAV support was attempted quite some years ago, but never finished. I don't think that anyone who is still active here has both time and knowledge to finish this.

In theory, the polyploid phasing algorithm could also phase diploids (by specifying ploidy 2), but in tests I made back then, the native diploid phaser yields much better results. I think for diploid samples your strategy should work fine, because if you change both the allele sequences and the genotypes of a single variant consistently, the results should be the same in the end. The limitation here is, that the modified variant has to be bi-allelic, i.e. there must not be a third allele sequence specified. Changing the order of the alleles within a variant, such that your sample only has zeroes and ones left in the genotype, would not be sufficient.

**Comment by sstwins21** [comment]
Thank you so much for the reply. 

Just to clarify, even for the bi-allelic sites, the alt column can have two genotypes, if the sample called for SNPs have heterozygous, but don't have the reference allele. Hence having genotype 1,2. So to make the genotype 0,1 for the given locus, I need to change the reference column in the VCF file. But, I noticed that for phase command in whatshap, it does require the reference genome and it worries me that changing the ref column in the VCF file might hinder the algorithm...
But would it be alright to change the ref if I want to use whatshap phase ?

Kind regards,
Shane

**Comment by schrins** [comment]
Closing this, because the questions seem to be answered. If any clarification is needed, feel free to re-open this issue.
