### ISSUE TITLE
Wh compare inconsistent switch-flip and switch-error results

### ISSUE THREAD

**Issue by pabloangulo7** [whatshap/whatshap#532]
Hello,

I would like to ask about the meaning of some results that seem inconsistent with what is explained in the guide. Specifically, the comparison between a truth set and a whatshap test in the switch errors and switch/flip decomposition sections. According to the guide, for the switchflips, the first number is the switches that are not part of a flip and the second number is the flip errors. So in the first log, if the switchflip is 49.99/10, the total number of switch errors would be 49.99 + 2*10 = 69.99. Instead, it appears that all the switch errors are 52.6 How is this possible? Secondly, I have another log where the switch/flip decomposition is 0.0/7.666666666666667 so there should be 14 switch errors but there are 0 in the logfile. What is the explanation for these results?

Thanks in advance

Python 3.10.14
whatshap version: 2.2
installed with conda

commands:

whatshap polyphase ${vcf_file} ${bam_file} --reference ${reference_fasta_file} -o ${vcf_phased_file} --ignore-read-groups --ploidy ${ploidy} --distrust-genotypes --threads ${threads}

whatshap compare --names ${haplotype},${sample} --ploidy 3 --ignore-sample-name ${vcf_truth_file} ${vcf_phased_file}

[Whatshap_log.txt](https://github.com/whatshap/whatshap/files/15013227/Whatshap_log.txt)
[Whatshap_log2.txt](https://github.com/whatshap/whatshap/files/15013229/Whatshap_log2.txt)

**Comment by schrins** [comment]
I did not look up the documentation of the error metrics, but the definition is as follows:
For the switch errors, we only consider variants that have the same genotype in both the true and the predicted phasing. Only for those variants, we count how many switches are required to transform the predicted phasing into the true one. Then, the number of switches is divided by the ploidy. If for some variant the order of all haplotypes was changed, this counts as one switch error. If only 2 out of 4 haplotypes were changed, it would count as 0.5 switch errors. This explains the fractional values for polyploid samples, while for diploids the number is always integer. Variants with diverging genotypes are ignored for this metric, because you cannot "repair" a wrong genotype by just rearranging the order of the predicted haplotypes - you need to modify single alleles as well.

The switch-flip errors are for that purpose: In addition to switches, it also introduces flips. A flip is the modification of a single allele on a single haplotype. For consistency, we normalize this by ploidy as well and say that the number of flip errors is the number of flips divided by the ploidy. The switch flip metric computes a transformation from predicted to true haplotypes such that the sum of switch errors and flip errors is minimized. This metric considers all common heterozygous variants, including those with diverging genotypes.

In your first log, you got 50 switch errors and 10 flip errors (the 49.9999999997 looks like some weird rounding error). This means that the "cheapest" way to edit the predicted haplotypes is to rearrange their order at 50 variants (or possibly more, because if only 2 out of 3 haplotypes change order, this event does not count as a full switch error) and additionally edit a total of 10*3 = 30 alleles (either all 3 alleles for 10 variant positions each, or 30 alleles scattered over single variants or something in between). Switches and flips are not comparable. It might be possible to find a transformation that, for example, uses 40 switch errors but 60 flip errors. Since 40+60 is larger than 50+10, the latter is reported.

The switch error rate is independent from the computation of the switch flip rate. In the first log, you have 24 variants with diverging genotypes. These variants are not considered for the pure switch error rate and if these excluded variants contain a lot of errors, the computation for the switch error rate might be quite different from the switch flip rate.

The difference between 50 and 52.666 is also not a contradiction: Imagine your predicted haplotypes are only wrong on a single variant, where two alleles are swapped between two haplotypes. If you want to repair this with switches only, you need to switch the order of two haplotypes in front of the variant and immediately change it back after the variant: A total of `4/ploidy` switch errors. If you can use both switches and flips, it is cheaper to use two flips for a total of `2/ploidy` flip errors. Thus, the switch error rate is higher than the switch flip rate.

Regarding your second log: Your predicted phasing is completely free of switch errors. You only have a total of 23 flips in there (7.6666*ploidy), which is perfectly in line with the 23 diverging genotypes. So apparently, there are 23 variants where the genotypes are 0/0/1 in one phasing and 0/1/1 in the other.

**Comment by pabloangulo7** [comment]
Thank you very much for the detailed reply, it is now clearer
